import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import clsx from "clsx";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dark SaaS Landing Page",
  description: "Generated by create next app",
  icons: {
    icon: "../app/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(raleway.className, "antialiased")}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
